[tool.black]
line-length = 70
target-version = ['py37']

[tool.basedpyright]
reportCallInDefaultInitializer = false
reportUnusedCallResult = false
reportAny = false

[tool.poetry.dependencies]
python = "^3.12"
