version: "3.8"

services:
  postgres:
    image: postgres:14.3-alpine3.16
    env_file:
      - .postgresql.env
    ports:
      - 5432:5432
    restart: always
    container_name: anime_die_heart_postgres
    volumes:
      - anime_die_heart_postgres:/var/lib/postgresql/data

volumes:
  anime_die_heart_postgres:
