# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: greet.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'greet.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bgreet.proto\x12\x05greet\x1a\x1fgoogle/protobuf/timestamp.proto\"0\n\x0eGreetMeRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x10\n\x08language\x18\x02 \x01(\t\"#\n\x0fGreetMeResponse\x12\x10\n\x08greeting\x18\x01 \x01(\t\"!\n\x1fSubscribeToNotificationsRequest\"\x93\x01\n SubscribeToNotificationsResponse\x12%\n\x04type\x18\x01 \x01(\x0e\x32\x17.greet.NotificationType\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x03 \x01(\t\x12\x18\n\x0bis_blocking\x18\x04 \x01(\x08H\x00\x88\x01\x01\x42\x0e\n\x0c_is_blocking\"|\n\x12UserActionsRequest\x12\x12\n\nuser_agent\x18\x01 \x01(\t\x12#\n\x04type\x18\x02 \x01(\x0e\x32\x15.greet.UserActionType\x12-\n\ttimestamp\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"\x15\n\x13UserActionsResponse\"6\n\x11\x46ileUploadRequest\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x12\x13\n\x0bpart_number\x18\x02 \x01(\x05\")\n\x12\x46ileUploadResponse\x12\x13\n\x0bpart_number\x18\x01 \x01(\x05*\x89\x01\n\x10NotificationType\x12\x1d\n\x19NOTIFICATION_TYPE_UNKNOWN\x10\x00\x12\x1a\n\x16NOTIFICATION_TYPE_INFO\x10\x01\x12\x1b\n\x17NOTIFICATION_TYPE_ERROR\x10\x02\x12\x1d\n\x19NOTIFICATION_TYPE_WARNING\x10\x03*J\n\x0eUserActionType\x12\x1c\n\x18USER_ACTION_TYPE_UNKNOWN\x10\x00\x12\x1a\n\x16USER_ACTION_TYPE_CLICK\x10\x01\x32\xc6\x02\n\x0cGreetService\x12\x38\n\x07GreetMe\x12\x15.greet.GreetMeRequest\x1a\x16.greet.GreetMeResponse\x12m\n\x18SubscribeToNotifications\x12&.greet.SubscribeToNotificationsRequest\x1a\'.greet.SubscribeToNotificationsResponse0\x01\x12\x46\n\x0bUserActions\x12\x19.greet.UserActionsRequest\x1a\x1a.greet.UserActionsResponse(\x01\x12\x45\n\nFileUpload\x12\x18.greet.FileUploadRequest\x1a\x19.greet.FileUploadResponse(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'greet_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_NOTIFICATIONTYPE']._serialized_start=576
  _globals['_NOTIFICATIONTYPE']._serialized_end=713
  _globals['_USERACTIONTYPE']._serialized_start=715
  _globals['_USERACTIONTYPE']._serialized_end=789
  _globals['_GREETMEREQUEST']._serialized_start=55
  _globals['_GREETMEREQUEST']._serialized_end=103
  _globals['_GREETMERESPONSE']._serialized_start=105
  _globals['_GREETMERESPONSE']._serialized_end=140
  _globals['_SUBSCRIBETONOTIFICATIONSREQUEST']._serialized_start=142
  _globals['_SUBSCRIBETONOTIFICATIONSREQUEST']._serialized_end=175
  _globals['_SUBSCRIBETONOTIFICATIONSRESPONSE']._serialized_start=178
  _globals['_SUBSCRIBETONOTIFICATIONSRESPONSE']._serialized_end=325
  _globals['_USERACTIONSREQUEST']._serialized_start=327
  _globals['_USERACTIONSREQUEST']._serialized_end=451
  _globals['_USERACTIONSRESPONSE']._serialized_start=453
  _globals['_USERACTIONSRESPONSE']._serialized_end=474
  _globals['_FILEUPLOADREQUEST']._serialized_start=476
  _globals['_FILEUPLOADREQUEST']._serialized_end=530
  _globals['_FILEUPLOADRESPONSE']._serialized_start=532
  _globals['_FILEUPLOADRESPONSE']._serialized_end=573
  _globals['_GREETSERVICE']._serialized_start=792
  _globals['_GREETSERVICE']._serialized_end=1118
# @@protoc_insertion_point(module_scope)
