# Generated by Django 4.0.5 on 2022-07-01 12:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('watch_list_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='file_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
