# Generated by Django 4.0.5 on 2022-07-07 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watch_list_app', '0003_movie_resized_files_absolute_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='resized_files_absolute_path',
        ),
        migrations.AddField(
            model_name='movie',
            name='mpd_file_absolute_path',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
